creation_rules:
  - path_regex: \.test\.yaml$
    encrypted_regex: ^(data|stringData)$
    pgp: 59E5F2DE820267D8E5D68C9F81EC941E1601C5D9
  - path_regex: \.accela\.yaml$
    encrypted_regex: ^(data|stringData)$
    pgp: 12EB812DFF3E923A1212F3B712FCE56D151F694F
  - path_regex: \.yaml$
    encrypted_regex: ^(data|stringData)$
    pgp: 91D51E2F33C4BDBAC06A A41FAFE2DD76B6E49C68
