creation_rules:
  - path_regex: \.test\.yaml$
    encrypted_regex: ^(data|stringData)$
    pgp: 59E5F2DE820267D8E5D68C9F81EC941E1601C5D9
  - path_regex: \.accela\.yaml$
    encrypted_regex: ^(data|stringData)$
    pgp: C0A6FC5232EDD2E48878333655F41A1C028BCFC4
  - path_regex: \.yaml$
    encrypted_regex: ^(data|stringData)$
    pgp: 7592549F0CE3DA293AA7E0E9B0E3B111BB3CA179
