apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: emissary
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./system/emissary/base
  dependsOn:
    - name: linkerd
  prune: true
  wait: true
  interval: 1m