apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: identity-issuer
  namespace: linkerd
spec:
  isCA: true
  commonName: identity.linkerd.cluster.local
  dnsNames:
  - identity.linkerd.cluster.local
  duration: 168h
  renewBefore: 25h
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: linkerd-identity-issuer
  issuerRef:
    name: trust-anchor
    kind: Issuer
