apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-cni
  namespace: linkerd-cni
spec:
  chart:
    spec:
      chart: linkerd2-cni
      sourceRef:
        kind: HelmRepository
        name: linkerd-edge
      version: 22.3.4
  interval: 1m
  values:
    # The namespace is already created by us
    installNamespace: false

    # Ignore the k8s API port. Required for Cilium because
    # of https://github.com/linkerd/linkerd2/issues/5932#issuecomment-816130423
    ignoreOutboundPorts: "6443"
