apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-multicluster
  namespace: linkerd-multicluster
spec:
  chart:
    spec:
      chart: linkerd-multicluster
      sourceRef:
        kind: HelmRepository
        name: linkerd-edge
      version: 30.0.10-edge
  interval: 1m
  dependsOn:
    - name: linkerd-control-plane
      namespace: linkerd