apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-multicluster
  namespace: linkerd-multicluster
spec:
  values:
    gateway:
      replicas: 3

    enablePodAntiAffinity: true