apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: linkerd-edge
  namespace: linkerd-cni
spec:
  interval: 1h
  url: https://helm.linkerd.io/edge
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: linkerd-edge
  namespace: linkerd
spec:
  interval: 1h
  url: https://helm.linkerd.io/edge
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: linkerd-edge
  namespace: linkerd-viz
spec:
  interval: 1h
  url: https://helm.linkerd.io/edge
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: linkerd-edge
  namespace: linkerd-jaeger
spec:
  interval: 1h
  url: https://helm.linkerd.io/edge
