apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/multicluster-link-accela.yaml
patchesStrategicMerge:
  - ../base/release-control-plane-ha.yaml
  - ../base/release-multicluster-ha.yaml
  - webhook-issuer.xerxes.enc.yaml
