name: Test

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup tools
        uses: ./.github/actions/tools
      - name: Setup Flux
        uses: fluxcd/flux2/action@main
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - name: Install Flux
        run: flux install
      - name: Setup cluster kustomization
        run: |
          flux create source git flux-system \
            --url=${{ github.event.repository.html_url }} \
            --branch=${GITHUB_REF#refs/heads/}
          flux create kustomization flux-system \
            --source=flux-system \
            --path=./clusters/test
      - name: Verify cluster reconciliation
        run: ./scripts/verify.sh
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          flux get all --all-namespaces
