apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emissary-ingress
  namespace: emissary-system
spec:
  chart:
    spec:
      chart: emissary-ingress
      sourceRef:
        kind: HelmRepository
        name: datawire
      version: 7.3.2
  interval: 1m
  values:
    agent:
      enabled: false
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: emissary-ingress
              namespace: emissary-system
            spec:
              template:
                metadata:
                  annotations:
                    linkerd.io/inject: ingress
                    config.linkerd.io/skip-inbound-ports: "80,443"
                    config.linkerd.io/proxy-require-identity-inbound-ports: "4183"
                spec:
                  containers:
                    - name: emissary-ingress
                      env:
                        - name: SCOUT_DISABLE
                          value: '1'